### ISSUE TITLE
Plugin failed to load with new recent release

### ISSUE THREAD

**Issue by oweitman** [danielvijge/lms_mixcloud#19]
If you need more information, please comment
i use the docker version of LMS.
what kind of compilation failed?

Logitech Media Server Version: 8.1.1 - 1610364019 @ Fri Jan 29 08:24:15 CET 2021
Hostname: 9dea11c46ff2
IP-Adresse des Servers: 192.168.1.82
Server-HTTP-Portnummer: 9000
Betriebssystem: Debian (Docker) - DE - utf8
Plattformarchitektur: x86_64-linux
Perl-Version: 5.24.1 - x86_64-linux-gnu-thread-multi
Audio::Scan: 1.02
IO::Socket::SSL: 2.044
Datenbankversion: DBD::SQLite 1.58 (sqlite 3.22.0)
Anzahl erkannter Player: 3

`[21-04-21 23:10:00.2739] Slim::bootstrap::tryModuleLoad (286) Warning: Module [Plugins::MixCloud::Plugin] failed to load:
Bareword "Slim::Utils::Misc::getTempDir" not allowed while "strict subs" in use at /config/cache/InstalledPlugins/Plugins/MixCloud/Buffered.pm line 23.
Compilation failed in require at /config/cache/InstalledPlugins/Plugins/MixCloud/ProtocolHandler.pm line 18.
BEGIN failed--compilation aborted at /config/cache/InstalledPlugins/Plugins/MixCloud/ProtocolHandler.pm line 21.
Compilation failed in require at /config/cache/InstalledPlugins/Plugins/MixCloud/Plugin.pm line 26.
BEGIN failed--compilation aborted at /config/cache/InstalledPlugins/Plugins/MixCloud/Plugin.pm line 26.
Compilation failed in require at (eval 923) line 1.
BEGIN failed--compilation aborted at (eval 923) line 1.

[21-04-21 23:10:00.2754] Slim::Utils::PluginManager::load (323) Error: Couldn't load Plugins::MixCloud::Plugin
`

**Comment by danielvijge** [comment]
#18
