### ISSUE TITLE
Mixcloud plugin stopped working

### ISSUE THREAD

**Issue by Esad-np** [danielvijge/lms_mixcloud#24]
as of this morning, the mixcloud plugin stopped working. The tracks are not playing. The error message in the log is :
22-03-03 09:21:58.7903] Plugins::MixCloud::ProtocolHandler::__ANON__ (200) Error getting play URL for mixcloud://gregbelson/the-blue-room-on-no-barriers-radio-2nd-march-2022/ => 404
 Not Found                                                                                                                                                                            
[22-03-03 09:21:58.7924] Slim::Player::Song::open (417) Error: Couldn't create command line for unk playback for [mixcloud://gregbelson/the-blue-room-on-no-barriers-radio-2nd-march-2
022/]

**Comment by danielvijge** [comment]
The site in which this plugin relies (https://www.dlmixcloud.com) seems to have stopped working. If that works again, this plugin work again. But as I have no control over that site, I cannot tell if it will work again or not.
If not, probably the quickest fix is to use a different mixcloud download side, such as https://mixclouddownloader.net/, that one still seems to work.

Not sure when I will have time to update it. In the meantime, a pull request is welcome. The code that needs changing is at https://github.com/danielvijge/lms_mixcloud/blob/master/ProtocolHandler.pm#L171. Make a POST request to the new download page, then extract from the HTML the correct link.

**Comment by kwarklabs** [comment]
Normal service resumed fo dlmixcloud.com so no immediate need to make any changes.
