### ISSUE TITLE
v0.8 - 404 File not Found

### ISSUE THREAD

**Issue by chieftobitobsn** [danielvijge/lms_mixcloud#27]
v0.7 runs perfectly after setting Network - Streaming Mode to persistent. After Update to v0.8 no connection is possible. Everything i do in the plugin ends up in 404 File not Found.

Do i need to change something inside LMS after Update v0.8?

cheers,
tobi

**Comment by kwarklabs** [comment]
@chieftobitobsn v0.9 should resolve this. Let us know how you get on once updated.

**Comment by chieftobitobsn** [comment]
@kwarklabs Plugin got back to work! Great fast work. Thx 👍
