### ISSUE TITLE
skipping forward in track not working

### ISSUE THREAD

**Issue by Tecko71** [danielvijge/lms_mixcloud#33]
I can not  skip  forward in a track. Resuming is not working either. I have premium. And some tracks do not play. But they do in mixcloud.
I have version V0.10  LMS V 8.4

**Comment by danielvijge** [comment]
Mixcloud doesn't have a public API to play tracks. Normally you're only allowed to play tracks either via their website or app. This plugin uses an available mixcloud downloader website to still get an URL for the track so it can be played. But this is nothing official, and for sure doesn't take into account if you have a paid subscription for Mixcloud.
As such there isn't that much I can do (*). The plugin just gets a URL for the track and passes this to the player to play. I cannot control about seeking or (un)pausing.

(*) There might be if someone is a real expect in the inner workings of LMS, and the network streams. I'm certainly not. I'm mainly doing critical bug fixes, but not any new development.
