### ISSUE TITLE
plugin failed to open mixes in sync players setup

### ISSUE THREAD

**Issue by jimydirektsaft** [danielvijge/lms_mixcloud#6]
Hi,  as soon as I try to open a mix on a synced player I get the follwoing warning in server.log:
`[19-08-19 13:15:35.2088] Slim::Player::Song::open (472) Warning: stream failed to open [mixcloud://abstrait/abstrait-384/]`
and the mix doesn't play on either of the synced players.

I can listen to mixes if I open the mix on the same un-snyced players.

This happens with Logitech Media Server Version: 7.9.1 and 7.9.2~1565967976 on a raspberry .
I tried with "Local Player", "SB Player" and "moode".

**Comment by kwarklabs** [comment]
Tested PR #25 successfully with synced players. Suggest closing once merged.
