### ISSUE TITLE
Repo xml still referring to 1.5 as version when 1.6 is released

### ISSUE THREAD

**Issue by PaulWebster** [danielvijge/lms_mixcloud#7]
Hi,
The version number shown in the repo xml is 1.5 - but it is pointing to the 1.6 download.
This means that users who already have 1.5 installed will not be prompted to install a new version.

**Comment by danielvijge** [comment]
Thanks for spotting this. It's fixed now in http://caterpillar.vijge.net/static/squeezebox/repo.xml
