### ISSUE TITLE
mixcloud 404 not found error

### ISSUE THREAD

**Issue by toolapcblack** [danielvijge/lms_mixcloud#8]
i am getting a have a "404 not found" error on mixcloud
on the Gui
home>mixcloud>mymixcloud >following 404 not found

Paul webster has kindly done a quick check and found the below

From a quick test on their site ... it looks like there now needs to be a "/" at the end

https://api.mixcloud.com/popular/

**Comment by PaulWebster** [comment]
See #9 for patch

**Comment by danielvijge** [comment]
Fixed by b32a3a27011b549ac4d929c8254f4682f4b8fdf4
